spring:
  application:
    name: springboot-department-docker
  datasource:
    url: jdbc:mysql://mysql:3307/deptdb
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9090

